In [ ]:
import numpy as np
import pandas as pd

# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# XOR input and output
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0], [1], [1], [0]])

# Seed for reproducibility
np.random.seed(42)

# Initialize weights and biases for 2-2-1 MLP
input_neurons = 2
hidden_neurons = 2
output_neurons = 1
lr = 0.5
epochs = 10000

# Random initial weights and biases
wh = np.random.uniform(size=(input_neurons, hidden_neurons))
bh = np.random.uniform(size=(1, hidden_neurons))
wo = np.random.uniform(size=(hidden_neurons, output_neurons))
bo = np.random.uniform(size=(1, output_neurons))

# Store initial weights and biases
initial_wh, initial_bh = wh.copy(), bh.copy()
initial_wo, initial_bo = wo.copy(), bo.copy()

# Training MLP
for epoch in range(epochs):
    # Forward pass
    hidden_input = np.dot(X, wh) + bh
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, wo) + bo
    final_output = sigmoid(final_input)

    # Error
    error = y - final_output

    # Backpropagation
    d_output = error * sigmoid_derivative(final_output)
    d_hidden = d_output.dot(wo.T) * sigmoid_derivative(hidden_output)

    # Update weights and biases
    wo += hidden_output.T.dot(d_output) * lr
    bo += np.sum(d_output, axis=0, keepdims=True) * lr
    wh += X.T.dot(d_hidden) * lr
    bh += np.sum(d_hidden, axis=0, keepdims=True) * lr

# Prepare tabular display of inputs and outputs
data = np.hstack((X, y, final_output))
df = pd.DataFrame(data, columns=["Input 1", "Input 2", "Expected Output", "MLP Output"])

# Print results
print("\n======= MULTILAYER PERCEPTRON (XOR) =======")
print(f"Number of epochs used: {epochs}\n")

print("Initial Hidden Layer Weights:\n", initial_wh)
print("Initial Hidden Layer Bias:\n", initial_bh)
print("Initial Output Layer Weights:\n", initial_wo)
print("Initial Output Layer Bias:\n", initial_bo, "\n")

print("Final Hidden Layer Weights:\n", wh)
print("Final Hidden Layer Bias:\n", bh)
print("Final Output Layer Weights:\n", wo)
print("Final Output Layer Bias:\n", bo, "\n")

print("===== INPUT AND FINAL OUTPUT TABLE =====")
print(df.to_string(index=False))
print("==========================================")



======= MULTILAYER PERCEPTRON (XOR) =======
Number of epochs used: 10000

Initial Hidden Layer Weights:
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
Initial Hidden Layer Bias:
 [[0.15601864 0.15599452]]
Initial Output Layer Weights:
 [[0.05808361]
 [0.86617615]]
Initial Output Layer Bias:
 [[0.60111501]] 

Final Hidden Layer Weights:
 [[4.59244504 6.47246975]
 [4.5971031  6.49153682]]
Final Hidden Layer Bias:
 [[-7.05239171 -2.8842842 ]]
Final Output Layer Weights:
 [[-10.32676834]
 [  9.62121009]]
Final Output Layer Bias:
 [[-4.44969307]] 

===== INPUT AND FINAL OUTPUT TABLE =====
 Input 1  Input 2  Expected Output  MLP Output
     0.0      0.0              0.0    0.018905
     0.0      1.0              1.0    0.983714
     1.0      0.0              1.0    0.983693
     1.0      1.0              0.0    0.016861
